# Example docker-compose.yml modification for GHCR
# Add this to your existing docker-compose.yml

services:
  frontend-nuxt:
    # Replace build section with image from GHCR
    image: ghcr.io/${GITHUB_REPOSITORY:-vinhltt/3_tihomo}/frontend-nuxt:${FRONTEND_IMAGE_TAG:-latest}
    
    # Remove the build section completely:
    # build:
    #   context: ./src/fe/nuxt
    #   dockerfile: Dockerfile
    
    container_name: ${COMPOSE_PROJECT_NAME:-tihomo}_frontend_nuxt
    restart: unless-stopped
    
    ports:
      - "${FRONTEND_PORT:-3500}:3000"
    
    environment:
      - NODE_ENV=production
      - NUXT_BUILD_TARGET=production
      - NUXT_DEV_SSR=false
      - NUXT_DEV_TOOLS=false
      - NUXT_DEBUG=false
      
    networks:
      - tihomo_network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    depends_on:
      ocelot-gateway:
        condition: service_healthy
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN:-localhost}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

# Note: Make sure to add these environment variables to your .env file:
# FRONTEND_IMAGE_TAG=latest
# GITHUB_REPOSITORY=vinhltt/3_tihomo
# COMPOSE_PROJECT_NAME=tihomo_development
