services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tihomo-cloudflared
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - tihomo-network
    # No direct dependencies - connects to services via network
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  tihomo-network:
    external: true