# TiHoMo Application Services Docker Compose
# Các services ứng dụng chính: Frontend, API Gateway, và các microservices

services:
  # ================================
  # APPLICATION SERVICES
  # ================================

  # Nuxt Frontend Application
  frontend-nuxt:
    build:
      context: ./src/fe/nuxt
      dockerfile: Dockerfile
      # Use environment variable to control build target
      target: ${NUXT_BUILD_TARGET:-development}
    container_name: tihomo-frontend-nuxt
    restart: unless-stopped
    environment:
      # Core Nuxt Configuration - environment-aware
      - NODE_ENV=${NODE_ENV:-development}
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - NUXT_DEV_SSR=${NUXT_DEV_SSR:-true}
      
      # API Configuration
      - API_BASE_URL=http://ocelot-gateway:8080
      
      # Authentication & Security
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NUXT_PUBLIC_API_BASE=${PUBLIC_API_BASE_URL:-http://ocelot-gateway:8080}
      - NUXT_PUBLIC_APP_BASE=${FRONTEND_BASE_URL}
      - NUXT_PUBLIC_GOOGLE_CLIENT_ID=${APP_PUBLIC_GOOGLE_CLIENT_ID}
      - NUXT_PUBLIC_FACEBOOK_APP_ID=${NUXT_PUBLIC_FACEBOOK_APP_ID}
      - OAUTH_REDIRECT_URI=${FRONTEND_BASE_URL}/auth/callback
      
      # Development & Debugging - environment-aware defaults
      - NUXT_DEBUG=${NUXT_DEBUG:-false}
      - NUXT_DEV_TOOLS=${NUXT_DEV_TOOLS:-true}
      - NUXT_TELEMETRY_DISABLED=1
      
      # Logging Configuration - environment-aware
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-dev}
      
      # Feature Toggles
      - ENABLE_PWA=${ENABLE_PWA:-false}
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-false}
      
      # Performance
      - NITRO_PRESET=node-server
      - NITRO_PORT=3000
    ports:
      - "${FRONTEND_PORT:-3500}:3000"  # Frontend Nuxt - LOCAL DEVELOPMENT ONLY
    volumes:
      # Always mount uploads and logs directories
      - ./uploads:/app/uploads
      - ./logs/frontend:/app/logs
      # Conditional source code mount - only in development with proper delegation
      - ${FRONTEND_SOURCE_MOUNT:-./src/fe/nuxt}:/app:delegated
      # Node modules volume to prevent overwrite by bind mount
      - frontend_node_modules:/app/node_modules
    networks:
      - tihomo-network
    depends_on:
      - ocelot-gateway
      - identity-api
      - corefinance-api
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 15s
      start_period: ${FRONTEND_HEALTHCHECK_START_PERIOD:-300s}  # 5 minutes for production build
      retries: 10

  # Ocelot API Gateway
  ocelot-gateway:
    build:
      context: ./src/be
      dockerfile: Ocelot.Gateway/Dockerfile
    container_name: tihomo-ocelot-gateway
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:8080
      - IsDocker=true
      - ConnectionStrings__Redis=redis:6379
      - Redis__Password=${REDIS_PASSWORD}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE_OCELOT_GATEWAY}
      - JwtSettings__AccessTokenExpirationMinutes=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:-60}
      - JwtSettings__RefreshTokenExpirationDays=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:-30}
      - Logging__LogLevel__Default=${API_LOG_LEVEL:-Information}
      # OtelSettings are now configured in appsettings.json
      - OtelSettings__ExporterOtlpEndpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://tempo:4317}
      - CorsSettings__AllowedOrigins__0=${CORS_ALLOWED_ORIGINS_0:-*}
      - CorsSettings__AllowedOrigins__1=${CORS_ALLOWED_ORIGINS_1:-}
      - CorsSettings__AllowedOrigins__2=${CORS_ALLOWED_ORIGINS_2:-}
      - CorsSettings__AllowedOrigins__3=${CORS_ALLOWED_ORIGINS_3:-}
      - CorsSettings__AllowedMethods__0=GET
      - CorsSettings__AllowedMethods__1=POST
      - CorsSettings__AllowedMethods__2=PUT
      - CorsSettings__AllowedMethods__3=DELETE
      - CorsSettings__AllowedMethods__4=OPTIONS
      - CorsSettings__AllowedHeaders__0=*
      - InternalServiceSettings__IdentityService=http://identity-api:8080
      - InternalServiceSettings__CoreFinanceService=http://corefinance-api:8080
    ports:
      - "${GATEWAY_PORT:-5800}:8080"  # API Gateway port - LOCAL DEVELOPMENT ONLY
    volumes:
      - ./src/be/Ocelot.Gateway/ocelot.Docker.json:/app/ocelot.json
      - ./logs/ocelot:/app/logs
    networks:
      - tihomo-network
    depends_on:
      - identity-api
      - corefinance-api
      - excel-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/identity/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Identity API Service
  identity-api:
    build:
      context: ./src/be
      dockerfile: Identity/Dockerfile
    container_name: tihomo-identity-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:8080
      - GOOGLE_CLIENT_ID=${APP_PUBLIC_GOOGLE_CLIENT_ID}
      - GoogleAuth__ClientId=${APP_PUBLIC_GOOGLE_CLIENT_ID}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - FacebookAuth__AppId=${FACEBOOK_APP_ID}
      - FacebookAuth__AppSecret=${FACEBOOK_APP_SECRET}
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE_IDENTITY_API}
      - JWT__AccessTokenExpirationMinutes=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:-60}
      - JWT__RefreshTokenExpirationDays=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:-30}
      # Updated connection string for unified database
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=identity;Username=identity_user;Password=identity_pass123
      - Redis__ConnectionString=redis:6379
      - Redis__Password=${REDIS_PASSWORD}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=tihomo
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - Logging__LogLevel__Default=${API_LOG_LEVEL:-Information}
      # OtelSettings are now configured in appsettings.json
      - OtelSettings__ExporterOtlpEndpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://tempo:4317}
    volumes:
      - ./logs/identity:/app/logs
    networks:
      - tihomo-network
    # Infrastructure dependencies removed - handled by docker-compose.infras.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CoreFinance API Service
  corefinance-api:
    build:
      context: ./src/be
      dockerfile: CoreFinance/Dockerfile
    container_name: tihomo-corefinance-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:8080
      # Updated connection string for unified database
      - ConnectionStrings__CoreFinanceDb=Host=postgres;Port=5432;Database=corefinance;Username=corefinance_user;Password=corefinance_pass123
      - ConnectionStrings__Redis=redis:6379
      - Redis__Password=${REDIS_PASSWORD}
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE_COREFINANCE_API}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=tihomo
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - IdentityService__BaseUrl=http://identity-api:8080
      - Logging__LogLevel__Default=${API_LOG_LEVEL:-Information}
      # OtelSettings are now configured in appsettings.json
      - OtelSettings__ExporterOtlpEndpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://tempo:4317}
      # CORS Configuration with multiple origins support
      - CorsOptions__PolicyName=${CORS_POLICY_NAME:-DefaultCorsPolicy}
      - CorsOptions__AllowedOrigins__0=${CORS_ALLOWED_ORIGINS_0:-*}
      - CorsOptions__AllowedOrigins__1=${CORS_ALLOWED_ORIGINS_1:-}
      - CorsOptions__AllowedOrigins__2=${CORS_ALLOWED_ORIGINS_2:-}
      - CorsOptions__AllowedOrigins__3=${CORS_ALLOWED_ORIGINS_3:-}
      - CorsOptions__AllowedMethods__0=GET
      - CorsOptions__AllowedMethods__1=POST
      - CorsOptions__AllowedMethods__2=PUT
      - CorsOptions__AllowedMethods__3=DELETE
      - CorsOptions__AllowedMethods__4=OPTIONS
      - CorsOptions__AllowedHeaders__0=*
      - CorsOptions__ExposedHeaders__0=${CORS_EXPOSED_HEADERS:-Token-Expired}
      - CorsOptions__PreflightMaxAgeInMinutes=${CORS_PREFLIGHT_MAX_AGE:-10}
    volumes:
      - ./logs/corefinance:/app/logs
    networks:
      - tihomo-network
    depends_on:
      - identity-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Excel API Service
  excel-api:
    build:
      context: ./src/be
      dockerfile: ExcelApi/Dockerfile
    container_name: tihomo-excel-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=tihomo
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - Redis__ConnectionString=redis:6379
      - Redis__Password=${REDIS_PASSWORD}
      - UploadPath=/app/uploads
      - Logging__LogLevel__Default=${API_LOG_LEVEL:-Information}
      # OtelSettings are now configured in appsettings.json
      - OtelSettings__ExporterOtlpEndpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://tempo:4317}
    volumes:
      - ./uploads:/app/uploads
      - ./logs/excel:/app/logs
    networks:
      - tihomo-network
    # Infrastructure dependencies removed - handled by docker-compose.infras.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3



# ================================
# NETWORKS
# ================================
networks:
  tihomo-network:
    external: true  # Sử dụng network từ docker-compose.infras.yml

# ================================
# VOLUMES
# ================================
volumes:
  # Frontend volumes
  frontend_node_modules:
    driver: local
  frontend_nuxt_cache:
    driver: local
  frontend_output:
    driver: local
  frontend_dist:
    driver: local
  frontend_cache:
    driver: local