# TiHoMo Cloudflare Tunnel Configuration
# Expose services qua Cloudflare Zero Trust Network

services:
  # ================================
  # CLOUDFLARE TUNNEL
  # ================================
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tihomo-cloudflared
    restart: unless-stopped
    environment:
      # Tunnel token - Lấy từ Cloudflare Zero Trust Dashboard
      # 1. Vào https://one.dash.cloudflare.com/
      # 2. Access > Tunnels > Create a tunnel
      # 3. Copy token và paste vào .env file
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - tihomo-network
    # No direct dependencies - connects to services via network
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# ================================
# NETWORKS
# ================================
networks:
  tihomo-network:
    external: true  # Sử dụng network từ docker-compose.infras.yml