version: '3.8'

services:
  # SSL Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: tihomo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/ssl/certs:/etc/ssl/certs
      - ./config/ssl/private:/etc/ssl/private
      - ./config/ssl/letsencrypt:/etc/letsencrypt
    depends_on:
      - ocelot-gateway
    restart: unless-stopped
    networks:
      - tihomo-network

  # Let's Encrypt Certificate Management
  certbot:
    image: certbot/certbot
    container_name: tihomo-certbot
    volumes:
      - ./config/ssl/letsencrypt:/etc/letsencrypt
      - ./config/ssl/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  # Ocelot Gateway (HTTP Only)
  ocelot-gateway:
    build:
      context: ./src/be/Ocelot.Gateway
      dockerfile: Dockerfile
    container_name: tihomo-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - JwtSettings__Issuer=https://api.tihomo.com
      - JwtSettings__Audience=tihomo-gateway
    expose:
      - "5000"
    depends_on:
      - identity-api
      - corefinance-api
    networks:
      - tihomo-network
    restart: unless-stopped

  # Identity Service
  identity-api:
    build:
      context: ./src/be/Identity
      dockerfile: Dockerfile
    container_name: tihomo-identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Host=identity-postgres;Database=identity;Username=identity_user;Password=${IDENTITY_DB_PASSWORD};Port=5432
    expose:
      - "5001"
    depends_on:
      - identity-postgres
    networks:
      - tihomo-network
    restart: unless-stopped

  # Core Finance Service
  corefinance-api:
    build:
      context: ./src/be/CoreFinance
      dockerfile: Dockerfile
    container_name: tihomo-corefinance
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5004
      - ConnectionStrings__CoreFinanceDb=Host=corefinance-postgres;Database=corefinance;Username=corefinance_user;Password=${COREFINANCE_DB_PASSWORD};Port=5432
    expose:
      - "5004"
    depends_on:
      - corefinance-postgres
    networks:
      - tihomo-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./src/fe/nuxt
      dockerfile: Dockerfile
    container_name: tihomo-frontend
    environment:
      - NUXT_PUBLIC_API_BASE=https://api.tihomo.com
      - NUXT_PUBLIC_IDENTITY_API_BASE=https://api.tihomo.com
    expose:
      - "3500"
    networks:
      - tihomo-network
    restart: unless-stopped

  # Databases
  identity-postgres:
    image: postgres:15
    container_name: tihomo-identity-postgres
    environment:
      - POSTGRES_DB=identity
      - POSTGRES_USER=identity_user
      - POSTGRES_PASSWORD=${IDENTITY_DB_PASSWORD}
    volumes:
      - identity_data:/var/lib/postgresql/data
    networks:
      - tihomo-network
    restart: unless-stopped

  corefinance-postgres:
    image: postgres:15
    container_name: tihomo-corefinance-postgres
    environment:
      - POSTGRES_DB=corefinance
      - POSTGRES_USER=corefinance_user
      - POSTGRES_PASSWORD=${COREFINANCE_DB_PASSWORD}
    volumes:
      - corefinance_data:/var/lib/postgresql/data
    networks:
      - tihomo-network
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    container_name: tihomo-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - tihomo-network
    restart: unless-stopped

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tihomo-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=tihomo
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - tihomo-network
    restart: unless-stopped

volumes:
  identity_data:
  corefinance_data:

networks:
  tihomo-network:
    driver: bridge 