apiVersion: 1

apps:
  - type: 'traces'
    orgId: 1
    disabled: false
    jsonData:
      datasourceUid: 'jaeger'
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['correlation_id', 'correlation.id', 'traceID']
        mappedTags:
          - key: 'correlation_id'
            value: 'correlation_id'
          - key: 'service.name'
            value: 'service_name'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags:
          - key: 'service.name'
            value: 'service_name'
        queries:
          - name: 'Request Rate'
            query: 'rate(http_requests_total{service_name="${__tag_service.name}"}[5m])'