global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # Metrics retention - keep for 30 days (adjust as needed)
  external_labels:
    environment: 'development'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'identity-api'
    static_configs:
      - targets: ['identity-api:5228']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'corefinance-api'
    static_configs:
      - targets: ['corefinance-api:5001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'excel-api'  
    static_configs:
      - targets: ['excel-api:5002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'ocelot-gateway'
    static_configs:
      - targets: ['ocelot-gateway:7293']
    metrics_path: '/metrics'
    scrape_interval: 15s
